### PR TITLE
Photos and limegreen dark theme text.

### PR DESCRIPTION
**Pull request by JaceTheKiller22**

### CODE REVIEW

**Comment by JaceTheKiller22** [comment]
Did I do this right? I think I did. Added some images for now and felt like a lime green fits the dark theme better.

**Comment by JaceTheKiller22** [comment]
Oh, I figured it out, I accidentally put the stuff in a folder called "foster-club-website."

**Comment by koukel** [comment]
I merged what you had.  I see that you added the files to the resources folder, but I don't see any changes when I view the website?

**Comment by JaceTheKiller22** [comment]
Yeah it's because I accidently made a seperate folder for the changes called "foster club website" I will try to re-pull request

**Comment by koukel** [comment]
OHHHHH, ok that makes sense.  Yeah, I don't know if there is an images file in the resources folder yet where the CSS and javascript folders are, so it's probably best to put them in there with the other assets.

**Pull request merged**
